# Generated by Django 3.0.5 on 2020-05-31 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0005_auto_20200524_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groupcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupcode', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='questiontable',
            name='auther',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userfollowing',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='questiontable',
            name='group_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Groupcode'),
        ),
    ]
