# Generated by Django 3.0.5 on 2020-06-01 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20200601_1408'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfollowers',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='userfollowing',
            unique_together=set(),
        ),
    ]
