# Generated by Django 3.0.5 on 2020-06-02 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0010_auto_20200602_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfollowing',
            name='followers',
        ),
        migrations.AddField(
            model_name='userfollowing',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
