# Generated by Django 3.0.5 on 2020-06-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20200614_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profilepic.png', null=True, upload_to='polls/profile_pic'),
        ),
    ]
