# Generated by Django 3.0.5 on 2020-06-21 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20200614_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiontable',
            name='group_code',
        ),
        migrations.AddField(
            model_name='questiontable',
            name='groupcode',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.DeleteModel(
            name='Groupcode',
        ),
    ]
