# Generated by Django 3.0.5 on 2020-06-21 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_auto_20200621_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiontable',
            name='op3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='questiontable',
            name='op4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
