# Generated by Django 3.0.5 on 2020-09-02 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_auto_20200903_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiontable',
            name='groupcode',
        ),
    ]
