# Generated by Django 3.0.5 on 2020-09-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_given_ans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='given_ans',
            name='question',
            field=models.CharField(max_length=300),
        ),
    ]
