# Generated by Django 3.0.5 on 2020-09-03 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0023_auto_20200903_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='given_ans',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.QuestionTable'),
        ),
    ]
