# Generated by Django 3.0.5 on 2020-09-03 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0024_auto_20200903_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiontable',
            name='auther',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.UserFollowing'),
        ),
    ]
